# Generated by Django 2.0.1 on 2018-02-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=128)),
                ('ctime', models.DateTimeField()),
                ('read_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
                ('home_choice_id', models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'Nginx'), (4, 'Mysql')])),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('detail2article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article2detail', to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleM2MTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('suffix', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('theme', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('comment2article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article2comment', to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UpDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.IntegerField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('u1_to_u2', models.ManyToManyField(related_name='u2_to_u1', to='repository.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WarningTable',
            fields=[
                ('UUID', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=3096)),
                ('status_id', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('process_time', models.DateTimeField(null=True)),
                ('creator2userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo2creator', to='repository.UserInfo')),
                ('processor2userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo2processor', to='repository.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='updown',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment2userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo2comment', to='repository.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='repository.Comment'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog2userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo2blog', to='repository.UserInfo', unique=True),
        ),
        migrations.AddField(
            model_name='articletype',
            name='articletype2blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog2articletype', to='repository.Blog'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='articleTag2blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog2articleTag', to='repository.Blog'),
        ),
        migrations.AddField(
            model_name='articlem2mtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleTag'),
        ),
        migrations.AddField(
            model_name='article',
            name='article2articletag',
            field=models.ManyToManyField(related_name='articletag2article', to='repository.ArticleTag'),
        ),
        migrations.AddField(
            model_name='article',
            name='article2articletype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aritcletype2article', to='repository.ArticleType'),
        ),
        migrations.AddField(
            model_name='article',
            name='article2blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog2article', to='repository.Blog'),
        ),
        migrations.AddField(
            model_name='article',
            name='article2userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='updown',
            unique_together={('article', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='articlem2mtag',
            unique_together={('article', 'tag')},
        ),
    ]
