# Generated by Django 2.0.1 on 2018-02-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog2userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo2blog', to='repository.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.IntegerField(null=True),
        ),
    ]
